language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.2.0
- ruby-head
env:
  matrix:
  - RAILS_VERSION=4.1.0
  - RAILS_VERSION=4.2.0
  global:
  - secure: qXpWydxv6DHMrvGL8WH4wNRY4MTY7KV/x308Y5dHkZCrI7k9UOccvznp69KT3Z+tzYEFDXfUix5wA6pgyVcvrsQyiLSjGcyzHhxJKs1gk0gcxAkmhwHmUP9aiXWUe/mzpj7Uoc2DHwpPTpK1wQ5kV6eV+jzQLuN3nhfNr2sL8b4=
script: bundle exec rake test
