language: ruby
rvm:
- 2.2.6
- 2.3.3
env:
  matrix:
  - RAILS_VERSION=4.1.10
  - RAILS_VERSION=4.2.1
  global:
  - secure: qXpWydxv6DHMrvGL8WH4wNRY4MTY7KV/x308Y5dHkZCrI7k9UOccvznp69KT3Z+tzYEFDXfUix5wA6pgyVcvrsQyiLSjGcyzHhxJKs1gk0gcxAkmhwHmUP9aiXWUe/mzpj7Uoc2DHwpPTpK1wQ5kV6eV+jzQLuN3nhfNr2sL8b4=
script: bundle exec rake test
